image: docker:latest

services:
  - docker:dind

stages:
- build

variables:
  CONTAINER_TEST_IMAGE: reg.surfnotify.com/$CI_PROJECT_ID:$CI_BUILD_REF_NAME_test
  CONTAINER_IMAGE: reg.surfnotify.com/surfnotify:$CI_BUILD_REF_NAME

before_script:
  - docker login -u reg -p $DOCKER_REG_PW my-docker-hub

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
