image: docker:latest

services:
  - docker:dind

stages:
- build

variables:
  CONTAINER_IMAGE: reg.surfnotify.com/surfnotify:latest

before_script:
  - docker login -u reg -p $DOCKER_REG_PW reg.surfnotify.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
