image: docker:latest

services:
  - docker:dind

stages:
- build
- test
- release
# - deploy

variables:
  DOCKER_DRIVER: overlay2
  SECRET_KEY_BASE: 89ffc4886ed96eb949d8f6f29a1cbd3840f91371e641ad6a609b8fadd074b0d1452772f535d1e2fbe8170c0c4aa86ae7d4921a7543c3d80e86ba43697cc2eb19
  CONTAINER_IMAGE_NAME: surfnotify
  CONTAINER_REGISTRY_DOMAIN: reg.surfnotify.com
  CONTAINER_TEST_IMAGE: $CONTAINER_REGISTRY_DOMAIN/$CONTAINER_IMAGE_NAME:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY_DOMAIN/$CONTAINER_IMAGE_NAME:latest
  POSTGRES_TEST_DB: surfnotify_test
  POSTGRES_TEST_HOST: postgres
  POSTGRES_TEST_USER: postgres
  POSTGRES_TEST_PASSWORD: ""

build-image:
  stage: build
  script:
    - docker login -u reg -p $DOCKER_REG_PW $CONTAINER_REGISTRY_DOMAIN
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test-image:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  dependencies:
    - build-image
  services:
    - postgres:latest
  variables:
    RAILS_ENV: 'test'
  script:
    - rails db:create db:schema:load
    - rails test

release-image:
  stage: release
  dependencies:
    - build-image
    - test-image
  script:
    - docker login -u reg -p $DOCKER_REG_PW $CONTAINER_REGISTRY_DOMAIN
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

# deploy-image:
#   stage: deploy
#   dependencies:
#     - build-image
#     - test-image
#     - release-image
#   only:
#     - master