verson: 3
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'CyJ111CkWOZo0X'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:4.0.2-alpine
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  rails:
    build: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - redis
      - db
    ports: 3000:3000
    volumes:
      - ./:/usr/src/surfnotify
