version: '3.3'

services:
  db:
    environment: &default_env
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'CyJ111CkWOZo0X'
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:4.0.2-alpine
    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'
  rails:
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'CyJ111CkWOZo0X'
    build: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - redis
      - db
    ports:
      - 3000:5000
    volumes:
      - ./:/usr/src/surfnotify

volumes:
  postgres:
  redis:
