version: '3.3'

services:
  db:
    environment: &db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CyJ111CkWOZo0X
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    command: sh ./start_app.sh
    depends_on:
      - redis
      - db
      - nginx
    environment:
      <<: *db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: 99c599ce75cff5b9496287f9b23b18854b4fa08e37617653d58f299b10620d726bf6fcd956b2e04adb934e11d2a41ad078302afdc865f6c1fcd4c03e778df6d3
    ports:
      - 3000:3000
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginxlog:/var/log/nginx
      - surfnotify_ssl:/etc/ssl/surfnotify
  redis:
    image: redis:4.0.2-alpine
    command: redis-server
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  nginxlog:
  surfnotify_ssl: