version: '3.3'

services:
  db:
    environment: &db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CyJ111CkWOZo0X
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build: ./
    # command: sh ./start_app.sh
    depends_on:
      - redis
      - db
    environment:
      <<: *db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: 99c599ce75cff5b9496287f9b23b18854b4fa08e37617653d58f299b10620d726bf6fcd956b2e04adb934e11d2a41ad078302afdc865f6c1fcd4c03e778df6d3
      VIRTUAL_HOST: 'surfnotify.com,www.surfnotify.com'
      LETSENCRYPT_HOST: 'surfnotify.com,www.surfnotify.com'
      LETSENCRYPT_EMAIL: 'info@surfnotify.com'
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/etc/nginx/vhost.d
      - nginx:/usr/share/nginx/html
      - nginx:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on: nginx-proxy
    volumes:
      - nginx:/etc/nginx/vhost.d
      - nginx:/usr/share/nginx/html
      - nginx:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: redis:4.0.2-alpine
    command: redis-server
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  nginx:
