version: '2'

services:
  app:
    image: reg.surfnotify.com/surfnotify:latest
    restart: always
    environment: &settings
      MAILER_ADDRESS: ${MAILER_ADDRESS}
      MAILER_PW: ${MAILER_PW}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      public:
  worker:
    image: reg.surfnotify.com/surfnotify:latest
    command: 'worker'
    restart: always
    environment:
      <<: *settings
    networks:
      - public
  scheduler:
    image: reg.surfnotify.com/surfnotify:latest
    command: 'scheduler'
    restart: always
    environment:
      <<: *settings
    networks:
      - public

networks:
  public:
    external:
      name: public
