default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: surfnotify_development
  host: docker
  username: postgres

test:
  <<: *default
  database: surfnotify_test
  host: docker
  username: postgres

production:
  <<: *default
  database: surfnotify_production
  host: postgres
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
